name: zet_ssh
description: Desktop terminal emulator built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  xterm: ^4.0.0
  pty:
    path: vendor/pty
  window_manager: ^0.5.1
  desktop_multi_window: ^0.2.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
